from backend.database import SessionLocal, RecipeModel, RecipeStepModel

recipes = [
    {
        "id": "italian_tomato_basil_pasta_veg",
        "name": "Tomato Basil Pasta",
        "cuisine": "mediterranean",
        "equipment": ["hob"],
        "ingredients": ["penne pasta", "olive oil", "garlic", "canned tomatoes", "cherry tomatoes", "fresh basil", "salt", "black pepper", "parmesan"],
        "cost": 1.80,
        "img": "https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [620, 20, 96, 16],
        "steps": [
            {"number": 1, "text": "Cook pasta in salted water until al dente, then drain.", "duration_minutes": 10},
            {"number": 2, "text": "Sauté garlic in olive oil until fragrant."},
            {"number": 3, "text": "Add canned and fresh tomatoes, season, and simmer until slightly thickened.", "duration_minutes": 8},
            {"number": 4, "text": "Toss pasta through the sauce and finish with basil and parmesan."}
        ]
    },
    {
        "id": "indian_chana_masala_veg_gf",
        "name": "Chana Masala (Vegetarian, Gluten-Free)",
        "cuisine": "indian",
        "equipment": ["hob"],
        "ingredients": ["canned chickpeas", "onion", "garlic", "ginger", "canned tomatoes", "ground cumin", "ground coriander", "garam masala", "turmeric", "salt", "rice"],
        "cost": 2.10,
        "img": "https://images.unsplash.com/photo-1604908177522-432a6e4d4e15?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 24, 102, 10],
        "steps": [
            {"number": 1, "text": "Sauté onion until golden, then add garlic and ginger."},
            {"number": 2, "text": "Stir in spices and cook briefly until fragrant."},
            {"number": 3, "text": "Add tomatoes and chickpeas, then simmer until thick and rich.", "duration_minutes": 18},
            {"number": 4, "text": "Serve hot over cooked rice."}
        ]
    },
    {
        "id": "mexican_vegetarian_enchilada_bake",
        "name": "Vegetarian Enchilada Bake",
        "cuisine": "mexican",
        "equipment": ["oven", "hob"],
        "ingredients": ["tortilla wraps", "canned black beans", "sweetcorn", "bell pepper", "onion", "enchilada sauce", "cheddar", "cumin"],
        "cost": 2.80,
        "img": "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 28, 96, 24],
        "steps": [
            {"number": 1, "text": "Sauté onion and pepper until soft, then stir in beans, sweetcorn, and cumin."},
            {"number": 2, "text": "Fill tortillas with mixture, roll, and place in a baking dish."},
            {"number": 3, "text": "Pour enchilada sauce over and sprinkle with cheddar."},
            {"number": 4, "text": "Bake until bubbling and golden.", "duration_minutes": 20}
        ]
    },
    {
        "id": "japanese_teriyaki_chicken_gf",
        "name": "Teriyaki Chicken (Gluten-Free)",
        "cuisine": "japanese",
        "equipment": ["hob"],
        "ingredients": ["chicken thigh", "tamari", "honey", "rice vinegar", "garlic", "ginger", "sesame oil", "rice", "broccoli"],
        "cost": 4.50,
        "img": "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&w=800&q=80",
        "nutrition": [710, 46, 78, 22],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Pan-sear chicken until golden.", "duration_minutes": 6},
            {"number": 3, "text": "Mix tamari, honey, vinegar, garlic, and ginger, then pour over chicken."},
            {"number": 4, "text": "Simmer until sticky and cooked through.", "duration_minutes": 6},
            {"number": 5, "text": "Serve with rice and steamed broccoli."}
        ]
    },
    {
        "id": "thai_basil_tofu_veg_gf",
        "name": "Thai Basil Tofu (Vegetarian, Gluten-Free)",
        "cuisine": "thai",
        "equipment": ["hob"],
        "ingredients": ["firm tofu", "garlic", "chilli", "tamari", "lime", "basil", "green beans", "rice"],
        "cost": 2.60,
        "img": "https://images.unsplash.com/photo-1512058564366-c9e2f1a1c2f7?auto=format&fit=crop&w=800&q=80",
        "nutrition": [580, 28, 64, 22],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Fry tofu cubes until golden and crisp.", "duration_minutes": 8},
            {"number": 3, "text": "Add garlic and chilli and cook briefly."},
            {"number": 4, "text": "Stir in tamari and green beans, cook until tender.", "duration_minutes": 5},
            {"number": 5, "text": "Finish with lime and basil, then serve over rice."}
        ]
    },
    {
        "id": "british_bangers_and_mash",
        "name": "Bangers and Mash",
        "cuisine": "british",
        "equipment": ["hob"],
        "ingredients": ["pork sausage", "potato", "milk", "butter", "onion", "beef stock", "salt", "black pepper"],
        "cost": 3.20,
        "img": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&w=800&q=80",
        "nutrition": [780, 32, 70, 42],
        "steps": [
            {"number": 1, "text": "Boil potatoes until tender, then mash with milk and butter.", "duration_minutes": 18},
            {"number": 2, "text": "Pan-fry sausages until browned and cooked through.", "duration_minutes": 12},
            {"number": 3, "text": "Sauté sliced onion until caramelised.", "duration_minutes": 10},
            {"number": 4, "text": "Add stock to onions and simmer briefly for gravy.", "duration_minutes": 5},
            {"number": 5, "text": "Serve sausages over mash with onion gravy."}
        ]
    },
    {
        "id": "korean_spicy_pork_bulgogi_gf",
        "name": "Spicy Pork Bulgogi (Gluten-Free)",
        "cuisine": "korean",
        "equipment": ["hob"],
        "ingredients": ["pork strips", "tamari", "gochujang", "garlic", "ginger", "sesame oil", "rice", "cucumber"],
        "cost": 4.30,
        "img": "https://images.unsplash.com/photo-1553621042-f6e147245754?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 44, 76, 28],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Mix tamari, gochujang, garlic, and ginger to make marinade."},
            {"number": 3, "text": "Stir-fry pork until browned.", "duration_minutes": 6},
            {"number": 4, "text": "Add marinade and cook until sticky and cooked through.", "duration_minutes": 4},
            {"number": 5, "text": "Serve over rice with sliced cucumber."}
        ]
    },
    {
        "id": "american_bbq_chicken_slow_cooker_gf",
        "name": "Slow Cooker BBQ Chicken (Gluten-Free)",
        "cuisine": "american",
        "equipment": ["slow_cooker"],
        "ingredients": ["chicken breast", "bbq sauce gluten free", "onion", "garlic", "smoked paprika", "salt", "sweet potato"],
        "cost": 3.40,
        "img": "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 46, 68, 16],
        "steps": [
            {"number": 1, "text": "Place chicken, onion, garlic, paprika, and bbq sauce in slow cooker."},
            {"number": 2, "text": "Cook until tender and shreddable.", "duration_minutes": 300},
            {"number": 3, "text": "Roast sweet potatoes separately until tender.", "duration_minutes": 25},
            {"number": 4, "text": "Shred chicken and serve with sweet potato."}
        ]
    },
    {
        "id": "microwave_scrambled_eggs_spinach",
        "name": "Microwave Scrambled Eggs & Spinach",
        "cuisine": "american",
        "equipment": ["microwave"],
        "ingredients": ["egg", "milk", "spinach", "salt", "black pepper", "cheddar"],
        "cost": 1.60,
        "img": "https://images.unsplash.com/photo-1514516870926-2061a20b0c79?auto=format&fit=crop&w=800&q=80",
        "nutrition": [420, 30, 6, 32],
        "steps": [
            {"number": 1, "text": "Whisk eggs with milk, salt, and pepper in a bowl."},
            {"number": 2, "text": "Microwave for 1 minute, stir, then microwave again until softly set.", "duration_minutes": 2},
            {"number": 3, "text": "Stir in spinach and cheddar, then microwave briefly until melted.", "duration_minutes": 1}
        ]
    },
    {
        "id": "mediterranean_chicken_greek_salad_gf",
        "name": "Greek Chicken Salad (Gluten-Free)",
        "cuisine": "mediterranean",
        "equipment": ["hob"],
        "ingredients": ["chicken breast", "cucumber", "cherry tomatoes", "red onion", "feta", "olive oil", "lemon", "oregano", "salt"],
        "cost": 4.90,
        "img": "https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80",
        "nutrition": [520, 44, 16, 30],
        "steps": [
            {"number": 1, "text": "Season chicken with oregano and salt, then cook in a pan until done.", "duration_minutes": 10},
            {"number": 2, "text": "Chop cucumber, tomatoes, and onion into a bowl."},
            {"number": 3, "text": "Slice chicken and add to salad with feta."},
            {"number": 4, "text": "Dress with olive oil and lemon before serving."}
        ]
    },
    {
        "id": "mexican_slow_cooker_vegetarian_chili_gf",
        "name": "Slow Cooker Vegetarian Chili (Gluten-Free)",
        "cuisine": "mexican",
        "equipment": ["slow_cooker"],
        "ingredients": ["canned kidney beans", "canned black beans", "canned tomatoes", "onion", "bell pepper", "sweetcorn", "cumin", "chilli powder", "salt", "rice"],
        "cost": 2.30,
        "img": "https://images.unsplash.com/photo-1604908177522-432a6e4d4e15?auto=format&fit=crop&w=800&q=80",
        "nutrition": [650, 26, 110, 8],
        "steps": [
            {"number": 1, "text": "Add all ingredients except rice to slow cooker and stir."},
            {"number": 2, "text": "Cook until thick and flavoursome.", "duration_minutes": 360},
            {"number": 3, "text": "Cook rice separately and serve chili over rice.", "duration_minutes": 12}
        ]
    },
    {
        "id": "indian_butter_chicken",
        "name": "Butter Chicken",
        "cuisine": "indian",
        "equipment": ["hob"],
        "ingredients": ["chicken thigh", "onion", "garlic", "ginger", "tomato passata", "double cream", "butter", "garam masala", "ground cumin", "ground coriander", "paprika", "salt", "rice"],
        "cost": 4.80,
        "img": "https://images.unsplash.com/photo-7SiLKNvPyDc?auto=format&fit=crop&w=800&q=80",
        "nutrition": [690, 42, 62, 30],
        "steps": [
            {"number": 1, "text": "Dice the chicken and season with salt, paprika, cumin, and coriander."},
            {"number": 2, "text": "Sauté onion in butter until soft, then add garlic and ginger and cook until fragrant."},
            {"number": 3, "text": "Add chicken and cook until lightly browned on the outside."},
            {"number": 4, "text": "Stir in passata and garam masala, then simmer gently until the chicken is cooked through and the sauce thickens.", "duration_minutes": 18},
            {"number": 5, "text": "Stir in cream, warm through, then serve over rice."},
        ],
    },
    {
        "id": "mexican_beef_tacos_hob",
        "name": "Beef Taco Skillet",
        "cuisine": "mexican",
        "equipment": ["hob"],
        "ingredients": ["beef mince", "onion", "garlic", "canned black beans", "canned tomatoes", "sweetcorn", "ground cumin", "chilli powder", "salt", "lime", "cheddar", "lettuce"],
        "cost": 3.20,
        "img": "https://images.unsplash.com/photo-lP5MCM6nZ5A?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 38, 45, 32],
        "steps": [
            {"number": 1, "text": "Brown the beef mince in a pan, then add diced onion and cook until softened."},
            {"number": 2, "text": "Add garlic, cumin, and chilli powder and stir for 30 seconds."},
            {"number": 3, "text": "Stir in tomatoes, beans, and sweetcorn, then simmer until saucy.", "duration_minutes": 12},
            {"number": 4, "text": "Finish with lime juice and top with cheddar and shredded lettuce to serve."},
        ],
    },
    {
        "id": "japanese_miso_ginger_salmon",
        "name": "Miso Ginger Salmon with Rice",
        "cuisine": "japanese",
        "equipment": ["hob"],
        "ingredients": ["salmon fillet", "miso paste", "ginger", "garlic", "honey", "rice vinegar", "spring onion", "rice", "cucumber"],
        "cost": 6.40,
        "img": "https://images.unsplash.com/photo-BHp_Jv8b48E?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 41, 70, 28],
        "steps": [
            {"number": 1, "text": "Mix miso, grated ginger, crushed garlic, honey, and rice vinegar into a quick glaze."},
            {"number": 2, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 3, "text": "Pan-sear salmon, then brush with glaze and cook until just done.", "duration_minutes": 8},
            {"number": 4, "text": "Serve salmon over rice with sliced cucumber and spring onion."},
        ],
    },
    {
        "id": "thai_green_curry_chicken_gf",
        "name": "Thai Green Curry Chicken (Gluten-Free)",
        "cuisine": "thai",
        "equipment": ["hob"],
        "ingredients": ["chicken breast", "green curry paste", "coconut milk", "fish sauce", "lime", "green beans", "bell pepper", "basil", "rice"],
        "cost": 4.60,
        "img": "https://images.unsplash.com/photo-z5ScgNngzpo?auto=format&fit=crop&w=800&q=80",
        "nutrition": [680, 40, 66, 28],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Fry green curry paste briefly in a pot until fragrant."},
            {"number": 3, "text": "Add chicken and stir until coated, then pour in coconut milk."},
            {"number": 4, "text": "Add vegetables and simmer gently until chicken is cooked and veg is tender.", "duration_minutes": 12},
            {"number": 5, "text": "Season with fish sauce and lime, then stir in basil and serve with rice."},
        ],
    },
    {
        "id": "middle_eastern_chickpea_tagine_veg",
        "name": "Chickpea & Vegetable Tagine",
        "cuisine": "middle_eastern",
        "equipment": ["hob"],
        "ingredients": ["canned chickpeas", "onion", "garlic", "carrot", "courgette", "canned tomatoes", "tomato paste", "ground cumin", "ground cinnamon", "smoked paprika", "vegetable stock", "lemon", "couscous"],
        "cost": 2.60,
        "img": "https://images.unsplash.com/photo-MlcewVImrOM?auto=format&fit=crop&w=800&q=80",
        "nutrition": [610, 20, 98, 14],
        "steps": [
            {"number": 1, "text": "Sauté onion until soft, then add garlic and spices and cook until fragrant."},
            {"number": 2, "text": "Add carrots and courgette, stirring to coat in spices."},
            {"number": 3, "text": "Stir in chickpeas, tomatoes, tomato paste, and stock, then simmer until thick and tender.", "duration_minutes": 20},
            {"number": 4, "text": "Make couscous according to packet instructions.", "duration_minutes": 5},
            {"number": 5, "text": "Finish tagine with lemon juice and serve over couscous."},
        ],
    },
    {
        "id": "british_shepherds_pie",
        "name": "Shepherd’s Pie",
        "cuisine": "british",
        "equipment": ["oven", "hob"],
        "ingredients": ["lamb mince", "onion", "carrot", "peas", "tomato paste", "beef stock", "worcestershire sauce", "potato", "milk", "butter", "salt", "black pepper"],
        "cost": 3.90,
        "img": "https://images.unsplash.com/photo-eYRKj0vwUu4?auto=format&fit=crop&w=800&q=80",
        "nutrition": [760, 39, 78, 32],
        "steps": [
            {"number": 1, "text": "Boil potatoes until very tender, then mash with milk, butter, salt, and pepper.", "duration_minutes": 18},
            {"number": 2, "text": "Brown lamb mince, add onion and carrot, and cook until softened."},
            {"number": 3, "text": "Stir in tomato paste, stock, and worcestershire sauce, then simmer until thick.", "duration_minutes": 12},
            {"number": 4, "text": "Stir through peas, spoon into a dish, top with mash, and rough up the surface with a fork."},
            {"number": 5, "text": "Bake until bubbling and golden on top.", "duration_minutes": 20},
        ],
    },
    {
        "id": "chinese_chicken_veg_stir_fry",
        "name": "Chicken & Veg Stir-Fry",
        "cuisine": "chinese",
        "equipment": ["hob"],
        "ingredients": ["chicken breast", "garlic", "ginger", "broccoli", "carrot", "bell pepper", "spring onion", "soy sauce", "sesame oil", "honey", "rice"],
        "cost": 3.40,
        "img": "https://images.unsplash.com/photo-kTROrGtnm7U?auto=format&fit=crop&w=800&q=80",
        "nutrition": [650, 44, 78, 18],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Stir-fry chicken in a hot pan until nearly cooked."},
            {"number": 3, "text": "Add garlic, ginger, and vegetables, and stir-fry until crisp-tender.", "duration_minutes": 6},
            {"number": 4, "text": "Stir in soy sauce, honey, and a small drizzle of sesame oil, then toss and serve with rice."},
        ],
    },
    {
        "id": "mediterranean_oven_feta_veg_traybake_veg",
        "name": "Mediterranean Veg & Feta Traybake",
        "cuisine": "mediterranean",
        "equipment": ["oven"],
        "ingredients": ["courgette", "bell pepper", "red onion", "cherry tomatoes", "chickpeas", "feta", "olive oil", "dried oregano", "lemon", "salt", "black pepper"],
        "cost": 2.90,
        "img": "https://images.unsplash.com/photo-5ShlTCcdEnk?auto=format&fit=crop&w=800&q=80",
        "nutrition": [560, 22, 52, 30],
        "steps": [
            {"number": 1, "text": "Heat the oven and tip chopped veg and chickpeas into a tray, then toss with olive oil, oregano, salt, and pepper."},
            {"number": 2, "text": "Roast until the veg is caramelised and tender.", "duration_minutes": 25},
            {"number": 3, "text": "Scatter feta over the tray and return to the oven until warmed and lightly golden.", "duration_minutes": 8},
            {"number": 4, "text": "Finish with lemon juice and serve."},
        ],
    },
    {
        "id": "korean_bibimbap_easy",
        "name": "Easy Bibimbap Bowl",
        "cuisine": "korean",
        "equipment": ["hob"],
        "ingredients": ["rice", "beef mince", "spinach", "carrot", "cucumber", "egg", "gochujang", "soy sauce", "sesame oil", "garlic"],
        "cost": 4.20,
        "img": "https://images.unsplash.com/photo-SbHulgzS_eo?auto=format&fit=crop&w=800&q=80",
        "nutrition": [740, 36, 86, 28],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Brown beef mince with garlic, then season with soy sauce and a small drizzle of sesame oil.", "duration_minutes": 6},
            {"number": 3, "text": "Quickly sauté spinach until wilted and lightly salted.", "duration_minutes": 2},
            {"number": 4, "text": "Fry eggs to your preference.", "duration_minutes": 3},
            {"number": 5, "text": "Assemble bowls with rice, veg, beef, and egg, then serve with gochujang stirred through."},
        ],
    },
    {
        "id": "american_slow_cooker_beef_chili_gf",
        "name": "Slow Cooker Beef Chili (Gluten-Free)",
        "cuisine": "american",
        "equipment": ["slow_cooker"],
        "ingredients": ["beef mince", "onion", "garlic", "canned kidney beans", "canned tomatoes", "tomato paste", "ground cumin", "smoked paprika", "chilli powder", "salt", "lime", "rice"],
        "cost": 3.10,
        "img": "https://images.unsplash.com/photo-7SiLKNvPyDc?auto=format&fit=crop&w=800&q=80",
        "nutrition": [690, 41, 78, 22],
        "steps": [
            {"number": 1, "text": "Add beef mince, onion, garlic, beans, tomatoes, tomato paste, and spices to the slow cooker."},
            {"number": 2, "text": "Stir well, cover, and cook until rich and thick.", "duration_minutes": 360},
            {"number": 3, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 4, "text": "Finish chili with lime juice and serve over rice."},
        ],
    },
    {
        "id": "indian_slow_cooker_lentil_dal_veg_gf",
        "name": "Slow Cooker Red Lentil Dal (Vegetarian, Gluten-Free)",
        "cuisine": "indian",
        "equipment": ["slow_cooker"],
        "ingredients": ["red lentils", "onion", "garlic", "ginger", "canned tomatoes", "coconut milk", "ground turmeric", "ground cumin", "garam masala", "vegetable stock", "spinach", "rice", "salt"],
        "cost": 1.90,
        "img": "https://images.unsplash.com/photo-BHp_Jv8b48E?auto=format&fit=crop&w=800&q=80",
        "nutrition": [620, 26, 96, 16],
        "steps": [
            {"number": 1, "text": "Rinse lentils, then add to the slow cooker with onion, garlic, ginger, tomatoes, spices, and stock."},
            {"number": 2, "text": "Cook until the lentils are soft and creamy.", "duration_minutes": 240},
            {"number": 3, "text": "Stir in coconut milk and spinach, then heat until the spinach wilts.", "duration_minutes": 10},
            {"number": 4, "text": "Serve with cooked rice."},
        ],
    },
    {
        "id": "middle_eastern_slow_cooker_chicken_shawarma_bowls",
        "name": "Slow Cooker Chicken Shawarma Bowls",
        "cuisine": "middle_eastern",
        "equipment": ["slow_cooker"],
        "ingredients": ["chicken thigh", "onion", "garlic", "lemon", "ground cumin", "ground coriander", "smoked paprika", "salt", "greek yogurt", "cucumber", "tomato", "rice"],
        "cost": 4.10,
        "img": "https://images.unsplash.com/photo-aqVsmOdYPx0?auto=format&fit=crop&w=800&q=80",
        "nutrition": [700, 45, 74, 24],
        "steps": [
            {"number": 1, "text": "Add chicken, sliced onion, garlic, lemon juice, spices, and salt to the slow cooker and mix to coat."},
            {"number": 2, "text": "Cook until the chicken is very tender.", "duration_minutes": 300},
            {"number": 3, "text": "Shred the chicken with two forks and stir it back through the juices."},
            {"number": 4, "text": "Serve over rice with chopped cucumber and tomato, plus a spoon of yogurt on top."},
        ],
    },
    {
        "id": "microwave_mug_omelette",
        "name": "Microwave Mug Omelette",
        "cuisine": "american",
        "equipment": ["microwave"],
        "ingredients": ["egg", "milk", "cheddar", "spring onion", "salt", "black pepper"],
        "cost": 1.50,
        "img": "https://images.unsplash.com/photo-8oHjwj0iA34?auto=format&fit=crop&w=800&q=80",
        "nutrition": [360, 24, 4, 28],
        "steps": [
            {"number": 1, "text": "Grease a large mug, then whisk egg with a splash of milk, salt, and pepper."},
            {"number": 2, "text": "Stir in cheddar and spring onion."},
            {"number": 3, "text": "Microwave until the egg is mostly set, then stir gently.", "duration_minutes": 1},
            {"number": 4, "text": "Microwave again until fully set and puffed, then rest briefly before eating.", "duration_minutes": 1},
        ],
    },
    {
        "id": "microwave_mexican_bean_rice_bowl_gf_veg",
        "name": "Microwave Black Bean Rice Bowl (Vegetarian, Gluten-Free)",
        "cuisine": "mexican",
        "equipment": ["microwave"],
        "ingredients": ["microwave rice", "canned black beans", "sweetcorn", "salsa", "lime", "cheddar", "coriander"],
        "cost": 1.95,
        "img": "https://images.unsplash.com/photo-njZcghyLXKU?auto=format&fit=crop&w=800&q=80",
        "nutrition": [620, 23, 92, 18],
        "steps": [
            {"number": 1, "text": "Microwave rice according to the packet.", "duration_minutes": 2},
            {"number": 2, "text": "Drain beans, then microwave beans and sweetcorn in a bowl until hot.", "duration_minutes": 2},
            {"number": 3, "text": "Mix rice with beans, sweetcorn, salsa, and lime juice."},
            {"number": 4, "text": "Top with cheddar and coriander, then microwave briefly to melt the cheese.", "duration_minutes": 1},
        ],
    },
    {
        "id": "microwave_tuna_pesto_pasta",
        "name": "Microwave Tuna Pesto Pasta",
        "cuisine": "mediterranean",
        "equipment": ["microwave"],
        "ingredients": ["microwave pasta", "tinned tuna", "pesto", "frozen peas", "lemon", "black pepper"],
        "cost": 2.70,
        "img": "https://images.unsplash.com/photo-EDoy1yjPLV0?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 40, 86, 22],
        "steps": [
            {"number": 1, "text": "Microwave pasta according to the packet.", "duration_minutes": 3},
            {"number": 2, "text": "Microwave peas with a splash of water until hot.", "duration_minutes": 2},
            {"number": 3, "text": "Stir tuna, pesto, peas, and a squeeze of lemon through the hot pasta."},
            {"number": 4, "text": "Season with black pepper and serve."},
        ],
    },
    {
        "id": "thai_pad_thai_quick",
        "name": "Quick Pad Thai",
        "cuisine": "thai",
        "equipment": ["hob"],
        "ingredients": ["rice noodles", "chicken breast", "egg", "garlic", "spring onion", "bean sprouts", "peanuts", "lime", "fish sauce", "brown sugar", "rice vinegar"],
        "cost": 4.90,
        "img": "https://images.unsplash.com/photo-ev46iKW6GHU?auto=format&fit=crop&w=800&q=80",
        "nutrition": [780, 42, 94, 26],
        "steps": [
            {"number": 1, "text": "Soak rice noodles in hot water until pliable, then drain.", "duration_minutes": 8},
            {"number": 2, "text": "Stir-fry chicken with garlic until nearly cooked.", "duration_minutes": 5},
            {"number": 3, "text": "Push chicken aside, scramble the egg, then toss in noodles."},
            {"number": 4, "text": "Add fish sauce, brown sugar, and rice vinegar, then toss until glossy and hot.", "duration_minutes": 3},
            {"number": 5, "text": "Top with bean sprouts, peanuts, spring onion, and lime."},
        ],
    },
    {
        "id": "japanese_egg_fried_rice_veg",
        "name": "Egg Fried Rice (Vegetarian)",
        "cuisine": "japanese",
        "equipment": ["hob"],
        "ingredients": ["cooked rice", "egg", "peas", "carrot", "spring onion", "soy sauce", "sesame oil"],
        "cost": 1.85,
        "img": "https://images.unsplash.com/photo-lrDLcX7jqqA?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 22, 92, 20],
        "steps": [
            {"number": 1, "text": "Heat a pan and scramble the eggs, then remove to a plate."},
            {"number": 2, "text": "Stir-fry peas and diced carrot until hot and tender-crisp.", "duration_minutes": 4},
            {"number": 3, "text": "Add cooked rice and stir-fry until warmed through and separating.", "duration_minutes": 4},
            {"number": 4, "text": "Return egg, add soy sauce and a small drizzle of sesame oil, then toss and top with spring onion."},
        ],
    },
    {
        "id": "middle_eastern_shakshuka_veg_gf",
        "name": "Shakshuka (Vegetarian, Gluten-Free)",
        "cuisine": "middle_eastern",
        "equipment": ["hob"],
        "ingredients": ["egg", "onion", "garlic", "bell pepper", "canned tomatoes", "ground cumin", "smoked paprika", "salt", "black pepper", "feta", "parsley"],
        "cost": 2.30,
        "img": "https://images.unsplash.com/photo-KRYuPwvyEys?auto=format&fit=crop&w=800&q=80",
        "nutrition": [520, 26, 28, 34],
        "steps": [
            {"number": 1, "text": "Sauté onion and pepper until softened, then add garlic and spices."},
            {"number": 2, "text": "Add tomatoes, season well, and simmer until thickened.", "duration_minutes": 12},
            {"number": 3, "text": "Make wells, crack in eggs, cover, and cook until whites set." , "duration_minutes": 6},
            {"number": 4, "text": "Top with feta and parsley and serve."},
        ],
    },
    {
        "id": "mediterranean_quinoa_caprese_veg_gf",
        "name": "Caprese Quinoa Bowl (Vegetarian, Gluten-Free)",
        "cuisine": "mediterranean",
        "equipment": ["hob"],
        "ingredients": ["quinoa", "cherry tomatoes", "mozzarella", "basil", "olive oil", "balsamic vinegar", "salt", "black pepper"],
        "cost": 3.10,
        "img": "https://images.unsplash.com/photo-5ShlTCcdEnk?auto=format&fit=crop&w=800&q=80",
        "nutrition": [560, 24, 62, 24],
        "steps": [
            {"number": 1, "text": "Rinse quinoa, then simmer in water until fluffy.", "duration_minutes": 15},
            {"number": 2, "text": "Halve tomatoes and tear mozzarella and basil into a bowl."},
            {"number": 3, "text": "Cool quinoa slightly, then toss with olive oil, balsamic, salt, and pepper."},
            {"number": 4, "text": "Fold through tomatoes and mozzarella, then finish with basil."},
        ],
    },
    {
        "id": "american_oven_chicken_fajita_rice_bake_gf",
        "name": "Chicken Fajita Rice Bake (Gluten-Free)",
        "cuisine": "american",
        "equipment": ["oven", "hob"],
        "ingredients": ["chicken breast", "onion", "bell pepper", "rice", "canned tomatoes", "chicken stock", "ground cumin", "smoked paprika", "salt", "cheddar", "lime"],
        "cost": 3.80,
        "img": "https://images.unsplash.com/photo-_7qSbsR9I9I?auto=format&fit=crop&w=800&q=80",
        "nutrition": [760, 48, 92, 20],
        "steps": [
            {"number": 1, "text": "Sauté onion and peppers briefly, then stir in spices and diced chicken."},
            {"number": 2, "text": "Stir in rice, tomatoes, and stock, then tip into a baking dish."},
            {"number": 3, "text": "Bake covered until rice is tender and liquid absorbed.", "duration_minutes": 30},
            {"number": 4, "text": "Top with cheddar and bake until melted.", "duration_minutes": 8},
            {"number": 5, "text": "Finish with lime juice and serve."},
        ],
    },
    {
        "id": "chinese_veg_noodle_stir_fry_veg",
        "name": "Veggie Noodle Stir-Fry (Vegetarian)",
        "cuisine": "chinese",
        "equipment": ["hob"],
        "ingredients": ["egg noodles", "garlic", "ginger", "mushroom", "carrot", "broccoli", "soy sauce", "sesame oil", "spring onion"],
        "cost": 2.40,
        "img": "https://images.unsplash.com/photo-eLEvLmOW0tU?auto=format&fit=crop&w=800&q=80",
        "nutrition": [690, 22, 98, 22],
        "steps": [
            {"number": 1, "text": "Cook noodles according to the packet, then drain." , "duration_minutes": 6},
            {"number": 2, "text": "Stir-fry garlic and ginger briefly, then add vegetables and cook until crisp-tender.", "duration_minutes": 6},
            {"number": 3, "text": "Add noodles, soy sauce, and a small drizzle of sesame oil, then toss until hot."},
            {"number": 4, "text": "Top with spring onion and serve."},
        ],
    },
    {
        "id": "indian_palak_paneer_veg_gf",
        "name": "Palak Paneer (Vegetarian, Gluten-Free)",
        "cuisine": "indian",
        "equipment": ["hob"],
        "ingredients": ["paneer", "spinach", "onion", "garlic", "ginger", "tomato", "ground cumin", "garam masala", "turmeric", "double cream", "salt", "rice"],
        "cost": 3.70,
        "img": "https://images.unsplash.com/photo-1625944525533-473f1a3b1f8b?auto=format&fit=crop&w=800&q=80",
        "nutrition": [680, 30, 72, 30],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Sauté chopped onion until soft, then add garlic and ginger and cook briefly."},
            {"number": 3, "text": "Add spices and chopped tomato, then cook until the tomato breaks down.", "duration_minutes": 6},
            {"number": 4, "text": "Stir in spinach and cook until wilted, then blend until smooth."},
            {"number": 5, "text": "Cube paneer, pan-sear lightly, then stir into the spinach sauce with cream and warm through.", "duration_minutes": 5},
        ],
    },
    {
        "id": "mexican_chicken_tinga_bowls_gf",
        "name": "Chicken Tinga Bowls (Gluten-Free)",
        "cuisine": "mexican",
        "equipment": ["hob"],
        "ingredients": ["chicken breast", "onion", "garlic", "canned tomatoes", "chipotle paste", "ground cumin", "salt", "lime", "rice", "coriander"],
        "cost": 3.90,
        "img": "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=80",
        "nutrition": [710, 48, 86, 18],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Sauté onion until soft, then add garlic and cumin and stir briefly."},
            {"number": 3, "text": "Add tomatoes and chipotle paste, then simmer to thicken.", "duration_minutes": 10},
            {"number": 4, "text": "Stir in shredded cooked chicken and simmer until saucy.", "duration_minutes": 6},
            {"number": 5, "text": "Serve over rice with lime juice and coriander."},
        ],
    },
    {
        "id": "japanese_curry_veg_oven",
        "name": "Japanese Vegetable Curry",
        "cuisine": "japanese",
        "equipment": ["hob"],
        "ingredients": ["potato", "carrot", "onion", "garlic", "ginger", "curry powder", "vegetable stock", "soy sauce", "honey", "rice", "peas"],
        "cost": 2.20,
        "img": "https://images.unsplash.com/photo-1604909053197-1d86f2ed18a3?auto=format&fit=crop&w=800&q=80",
        "nutrition": [690, 16, 118, 14],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Sauté onion until translucent, then add garlic and ginger."},
            {"number": 3, "text": "Add potato and carrot, pour in stock, and simmer until tender.", "duration_minutes": 18},
            {"number": 4, "text": "Stir in curry powder, soy sauce, honey, and peas, then simmer until thick.", "duration_minutes": 6},
            {"number": 5, "text": "Serve curry over rice."},
        ],
    },
    {
        "id": "thai_red_curry_prawns_gf",
        "name": "Thai Red Curry Prawns (Gluten-Free)",
        "cuisine": "thai",
        "equipment": ["hob"],
        "ingredients": ["prawns", "red curry paste", "coconut milk", "fish sauce", "lime", "bell pepper", "green beans", "basil", "rice"],
        "cost": 6.20,
        "img": "https://images.unsplash.com/photo-1604908177030-cc2d1b6b5d0b?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 38, 74, 22],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Fry red curry paste briefly in a pot until fragrant."},
            {"number": 3, "text": "Add coconut milk and vegetables, then simmer until tender-crisp.", "duration_minutes": 8},
            {"number": 4, "text": "Add prawns and simmer until just cooked through.", "duration_minutes": 4},
            {"number": 5, "text": "Season with fish sauce and lime, stir in basil, and serve with rice."},
        ],
    },
    {
        "id": "middle_eastern_kofta_traybake",
        "name": "Middle Eastern Kofta Traybake",
        "cuisine": "middle_eastern",
        "equipment": ["oven", "hob"],
        "ingredients": ["beef mince", "onion", "garlic", "ground cumin", "ground coriander", "smoked paprika", "salt", "yogurt", "lemon", "cucumber", "tomato", "flatbread"],
        "cost": 4.10,
        "img": "https://images.unsplash.com/photo-1544511916-0148ccdeb877?auto=format&fit=crop&w=800&q=80",
        "nutrition": [780, 42, 70, 34],
        "steps": [
            {"number": 1, "text": "Heat the oven and line a tray."},
            {"number": 2, "text": "Mix mince with grated onion, garlic, spices, and salt, then shape into small koftas."},
            {"number": 3, "text": "Bake until browned and cooked through.", "duration_minutes": 16},
            {"number": 4, "text": "Mix yogurt with lemon juice for a quick sauce."},
            {"number": 5, "text": "Serve koftas with chopped cucumber and tomato and warmed flatbread.", "duration_minutes": 2},
        ],
    },
    {
        "id": "british_fish_pie_oven",
        "name": "Fish Pie",
        "cuisine": "british",
        "equipment": ["oven", "hob"],
        "ingredients": ["white fish fillet", "frozen peas", "milk", "butter", "onion", "cornflour", "potato", "salt", "black pepper"],
        "cost": 5.60,
        "img": "https://images.unsplash.com/photo-1604908177450-9b14c3c4b9c7?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 44, 86, 22],
        "steps": [
            {"number": 1, "text": "Boil potatoes until tender, then mash with a little milk and butter.", "duration_minutes": 18},
            {"number": 2, "text": "Sauté onion in butter, then whisk in milk and cornflour to make a thick sauce.", "duration_minutes": 6},
            {"number": 3, "text": "Fold fish and peas through the sauce and season well."},
            {"number": 4, "text": "Spoon into a dish, top with mash, and bake until bubbling and lightly golden.", "duration_minutes": 20},
        ],
    },
    {
        "id": "chinese_mapo_tofu_veg",
        "name": "Mapo Tofu (Vegetarian Style)",
        "cuisine": "chinese",
        "equipment": ["hob"],
        "ingredients": ["firm tofu", "mushroom", "garlic", "ginger", "spring onion", "chilli flakes", "doubanjiang", "soy sauce", "cornflour", "vegetable stock", "rice"],
        "cost": 2.90,
        "img": "https://images.unsplash.com/photo-1546069901-d5bfd2cbfb1f?auto=format&fit=crop&w=800&q=80",
        "nutrition": [670, 26, 92, 22],
        "steps": [
            {"number": 1, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 2, "text": "Sauté garlic and ginger, then stir in doubanjiang and chilli flakes."},
            {"number": 3, "text": "Add chopped mushrooms and cook until softened.", "duration_minutes": 5},
            {"number": 4, "text": "Add stock and soy sauce, then simmer gently with tofu cubes.", "duration_minutes": 8},
            {"number": 5, "text": "Thicken with cornflour slurry, top with spring onion, and serve with rice."},
        ],
    },
    {
        "id": "mediterranean_tuna_bean_salad_gf",
        "name": "Tuna and Bean Salad (Gluten-Free)",
        "cuisine": "mediterranean",
        "equipment": ["hob"],
        "ingredients": ["tinned tuna", "canned cannellini beans", "red onion", "cherry tomatoes", "parsley", "olive oil", "lemon", "salt", "black pepper"],
        "cost": 2.80,
        "img": "https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=800&q=80",
        "nutrition": [520, 38, 42, 22],
        "steps": [
            {"number": 1, "text": "Drain beans and tuna and place in a bowl."},
            {"number": 2, "text": "Add sliced onion, halved tomatoes, and chopped parsley."},
            {"number": 3, "text": "Dress with olive oil, lemon juice, salt, and pepper, then toss well."},
        ],
    },
    {
        "id": "korean_kimchi_fried_rice",
        "name": "Kimchi Fried Rice",
        "cuisine": "korean",
        "equipment": ["hob"],
        "ingredients": ["cooked rice", "kimchi", "egg", "spring onion", "soy sauce", "sesame oil", "gochujang", "peas"],
        "cost": 2.10,
        "img": "https://images.unsplash.com/photo-1604908177528-7b4f8d8b3d1a?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 22, 104, 24],
        "steps": [
            {"number": 1, "text": "Sauté kimchi briefly in a pan to drive off excess moisture.", "duration_minutes": 3},
            {"number": 2, "text": "Add rice and peas and stir-fry until hot and separating.", "duration_minutes": 5},
            {"number": 3, "text": "Stir in gochujang, soy sauce, and a small drizzle of sesame oil."},
            {"number": 4, "text": "Fry an egg and serve on top with spring onion."},
        ],
    },
    {
        "id": "american_turkey_chilli_slow_cooker_gf",
        "name": "Slow Cooker Turkey Chili (Gluten-Free)",
        "cuisine": "american",
        "equipment": ["slow_cooker"],
        "ingredients": ["turkey mince", "onion", "garlic", "canned kidney beans", "canned tomatoes", "tomato paste", "ground cumin", "smoked paprika", "chilli powder", "salt", "rice"],
        "cost": 3.40,
        "img": "https://images.unsplash.com/photo-1604908177512-0b4c4c6b8c8e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [690, 44, 86, 18],
        "steps": [
            {"number": 1, "text": "Add turkey mince, onion, garlic, beans, tomatoes, tomato paste, and spices to the slow cooker."},
            {"number": 2, "text": "Stir well, cover, and cook until thick and rich.", "duration_minutes": 360},
            {"number": 3, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 4, "text": "Serve chili over rice."},
        ],
    },
    {
        "id": "indian_slow_cooker_chicken_korma_gf",
        "name": "Slow Cooker Chicken Korma (Gluten-Free)",
        "cuisine": "indian",
        "equipment": ["slow_cooker"],
        "ingredients": ["chicken thigh", "onion", "garlic", "ginger", "coconut milk", "ground cumin", "garam masala", "ground turmeric", "ground almonds", "salt", "rice"],
        "cost": 4.30,
        "img": "https://images.unsplash.com/photo-1604908177444-4b9f7d2c9a1f?auto=format&fit=crop&w=800&q=80",
        "nutrition": [760, 46, 78, 30],
        "steps": [
            {"number": 1, "text": "Add chicken, onion, garlic, ginger, spices, coconut milk, almonds, and salt to the slow cooker."},
            {"number": 2, "text": "Cook until chicken is very tender and the sauce is creamy.", "duration_minutes": 300},
            {"number": 3, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 4, "text": "Serve korma over rice."},
        ],
    },
    {
        "id": "mexican_slow_cooker_pulled_pork",
        "name": "Slow Cooker Pulled Pork Bowls",
        "cuisine": "mexican",
        "equipment": ["slow_cooker"],
        "ingredients": ["pork shoulder", "onion", "garlic", "canned tomatoes", "ground cumin", "smoked paprika", "salt", "lime", "rice", "coriander"],
        "cost": 5.80,
        "img": "https://images.unsplash.com/photo-1544025162-8a8f6d2b1d3d?auto=format&fit=crop&w=800&q=80",
        "nutrition": [780, 44, 78, 34],
        "steps": [
            {"number": 1, "text": "Place pork, onion, garlic, tomatoes, spices, and salt into the slow cooker."},
            {"number": 2, "text": "Cook until the pork shreds easily.", "duration_minutes": 420},
            {"number": 3, "text": "Shred pork and mix through the juices."},
            {"number": 4, "text": "Serve with rice, lime, and coriander."},
        ],
    },
    {
        "id": "middle_eastern_slow_cooker_harissa_chickpeas_veg_gf",
        "name": "Slow Cooker Harissa Chickpeas (Vegetarian, Gluten-Free)",
        "cuisine": "middle_eastern",
        "equipment": ["slow_cooker"],
        "ingredients": ["canned chickpeas", "onion", "garlic", "harissa paste", "canned tomatoes", "carrot", "bell pepper", "vegetable stock", "salt", "lemon", "rice"],
        "cost": 2.10,
        "img": "https://images.unsplash.com/photo-1604908177488-3f2a1b9c6d1e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 22, 108, 10],
        "steps": [
            {"number": 1, "text": "Add chickpeas, onion, garlic, harissa, tomatoes, vegetables, stock, and salt to the slow cooker."},
            {"number": 2, "text": "Cook until flavours meld and vegetables are tender.", "duration_minutes": 300},
            {"number": 3, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 4, "text": "Finish with lemon juice and serve over rice."},
        ],
    },
    {
        "id": "american_slow_cooker_salsa_chicken_gf",
        "name": "Slow Cooker Salsa Chicken (Gluten-Free)",
        "cuisine": "american",
        "equipment": ["slow_cooker"],
        "ingredients": ["chicken breast", "salsa", "onion", "garlic", "ground cumin", "salt", "rice", "coriander"],
        "cost": 3.10,
        "img": "https://images.unsplash.com/photo-1604908177436-0d2b5b8f6a9c?auto=format&fit=crop&w=800&q=80",
        "nutrition": [660, 48, 86, 12],
        "steps": [
            {"number": 1, "text": "Add chicken, salsa, onion, garlic, cumin, and salt to the slow cooker."},
            {"number": 2, "text": "Cook until chicken is tender, then shred and mix back through.", "duration_minutes": 300},
            {"number": 3, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 4, "text": "Serve salsa chicken over rice with coriander."},
        ],
    },
    {
        "id": "microwave_gf_oatmeal_protein_bowl_veg_gf",
        "name": "Microwave Protein Oat Bowl (Vegetarian, Gluten-Free)",
        "cuisine": "american",
        "equipment": ["microwave"],
        "ingredients": ["gluten free oats", "milk", "greek yogurt", "banana", "peanut butter", "cinnamon"],
        "cost": 1.70,
        "img": "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=800&q=80",
        "nutrition": [560, 28, 72, 18],
        "steps": [
            {"number": 1, "text": "Combine oats and milk in a microwave-safe bowl."},
            {"number": 2, "text": "Microwave until thickened, stirring once halfway.", "duration_minutes": 3},
            {"number": 3, "text": "Top with yogurt, sliced banana, peanut butter, and cinnamon."},
        ],
    },
    {
        "id": "microwave_chicken_rice_steam_bowl_gf",
        "name": "Microwave Chicken Rice Bowl (Gluten-Free)",
        "cuisine": "chinese",
        "equipment": ["microwave"],
        "ingredients": ["microwave rice", "cooked chicken", "frozen broccoli", "carrot", "tamari", "sesame oil"],
        "cost": 2.90,
        "img": "https://images.unsplash.com/photo-1546069901-5ec6a79120b3?auto=format&fit=crop&w=800&q=80",
        "nutrition": [640, 38, 92, 14],
        "steps": [
            {"number": 1, "text": "Microwave rice according to packet instructions.", "duration_minutes": 2},
            {"number": 2, "text": "Microwave broccoli and sliced carrot with a splash of water until hot.", "duration_minutes": 3},
            {"number": 3, "text": "Stir chicken through rice, add veg, then season with tamari and a small drizzle of sesame oil."},
        ],
    },
    {
        "id": "microwave_lentil_soup_mug_veg_gf",
        "name": "Microwave Lentil Soup Mug (Vegetarian, Gluten-Free)",
        "cuisine": "middle_eastern",
        "equipment": ["microwave"],
        "ingredients": ["canned lentils", "vegetable stock", "tomato paste", "garlic", "ground cumin", "lemon", "salt", "black pepper"],
        "cost": 1.60,
        "img": "https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=800&q=80",
        "nutrition": [420, 22, 62, 8],
        "steps": [
            {"number": 1, "text": "Add lentils, stock, tomato paste, garlic, cumin, salt, and pepper to a large microwave-safe mug and stir."},
            {"number": 2, "text": "Microwave until piping hot, stirring once.", "duration_minutes": 3},
            {"number": 3, "text": "Finish with lemon juice and serve."},
        ],
    },
    {
        "id": "microwave_potato_beans_cheese_veg_gf",
        "name": "Microwave Jacket Potato with Beans (Vegetarian, Gluten-Free)",
        "cuisine": "british",
        "equipment": ["microwave"],
        "ingredients": ["potato", "baked beans", "cheddar", "salt", "black pepper"],
        "cost": 1.90,
        "img": "https://images.unsplash.com/photo-1541592106381-2f2f52c4f51c?auto=format&fit=crop&w=800&q=80",
        "nutrition": [650, 26, 96, 18],
        "steps": [
            {"number": 1, "text": "Pierce the potato all over with a fork and microwave until tender, turning once.", "duration_minutes": 8},
            {"number": 2, "text": "Split the potato, season, then add baked beans."},
            {"number": 3, "text": "Top with cheddar and microwave until melted.", "duration_minutes": 1},
        ],
    },
    {
        "id": "microwave_couscous_feta_bowl_veg",
        "name": "Microwave Couscous and Feta Bowl (Vegetarian)",
        "cuisine": "mediterranean",
        "equipment": ["microwave"],
        "ingredients": ["couscous", "vegetable stock", "cucumber", "cherry tomatoes", "feta", "olive oil", "lemon", "salt", "black pepper"],
        "cost": 2.10,
        "img": "https://images.unsplash.com/photo-1546069901-7a9f4f0e8b6d?auto=format&fit=crop&w=800&q=80",
        "nutrition": [610, 20, 86, 22],
        "steps": [
            {"number": 1, "text": "Add couscous and stock to a bowl and microwave until the liquid is absorbed.", "duration_minutes": 2},
            {"number": 2, "text": "Fluff couscous with a fork, then stir in chopped cucumber and tomatoes."},
            {"number": 3, "text": "Top with feta and dress with olive oil, lemon, salt, and pepper."},
        ],
    },
    {
        "id": "mediterranean_oven_lemon_oregano_chicken",
        "name": "Lemon Oregano Chicken Traybake",
        "cuisine": "mediterranean",
        "equipment": ["oven"],
        "ingredients": ["chicken thigh", "potato", "red onion", "lemon", "olive oil", "dried oregano", "garlic", "salt", "black pepper"],
        "cost": 4.40,
        "img": "https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?auto=format&fit=crop&w=800&q=80",
        "nutrition": [760, 44, 72, 32],
        "steps": [
            {"number": 1, "text": "Heat the oven and toss potatoes and onion with olive oil, salt, pepper, and oregano."},
            {"number": 2, "text": "Add chicken and crushed garlic, then squeeze over lemon and add the wedges to the tray."},
            {"number": 3, "text": "Bake until chicken is cooked and potatoes are golden.", "duration_minutes": 35},
            {"number": 4, "text": "Rest briefly, then serve with pan juices."},
        ],
    },
    {
        "id": "american_oven_mac_and_cheese",
        "name": "Baked Mac and Cheese",
        "cuisine": "american",
        "equipment": ["oven", "hob"],
        "ingredients": ["macaroni", "butter", "milk", "cheddar", "parmesan", "cornflour", "salt", "black pepper"],
        "cost": 2.70,
        "img": "https://images.unsplash.com/photo-1543339308-43e59d6b73a6?auto=format&fit=crop&w=800&q=80",
        "nutrition": [780, 32, 92, 34],
        "steps": [
            {"number": 1, "text": "Cook macaroni until just al dente, then drain.", "duration_minutes": 8},
            {"number": 2, "text": "Make a cheese sauce by melting butter, whisking in cornflour, then adding milk and simmering until thick.", "duration_minutes": 6},
            {"number": 3, "text": "Stir in cheddar and parmesan until melted, then season."},
            {"number": 4, "text": "Mix pasta with sauce, transfer to a dish, and bake until bubbling.", "duration_minutes": 15},
        ],
    },
    {
        "id": "chinese_egg_drop_soup_gf",
        "name": "Egg Drop Soup (Gluten-Free)",
        "cuisine": "chinese",
        "equipment": ["hob"],
        "ingredients": ["egg", "chicken stock", "spring onion", "cornflour", "sesame oil", "salt", "white pepper"],
        "cost": 1.70,
        "img": "https://images.unsplash.com/photo-1547592180-0f10f9d3b85c?auto=format&fit=crop&w=800&q=80",
        "nutrition": [320, 18, 10, 22],
        "steps": [
            {"number": 1, "text": "Bring stock to a simmer and season lightly."},
            {"number": 2, "text": "Stir in a small cornflour slurry to lightly thicken.", "duration_minutes": 2},
            {"number": 3, "text": "Slowly pour in beaten egg while stirring to form ribbons.", "duration_minutes": 1},
            {"number": 4, "text": "Finish with spring onion and a tiny drizzle of sesame oil."},
        ],
    },
    {
        "id": "korean_ginger_soy_meatballs",
        "name": "Ginger Soy Meatballs",
        "cuisine": "korean",
        "equipment": ["oven", "hob"],
        "ingredients": ["pork mince", "garlic", "ginger", "spring onion", "soy sauce", "honey", "sesame oil", "rice", "cucumber"],
        "cost": 4.50,
        "img": "https://images.unsplash.com/photo-1529692236671-2f2b9e6f2f7f?auto=format&fit=crop&w=800&q=80",
        "nutrition": [760, 36, 82, 32],
        "steps": [
            {"number": 1, "text": "Heat the oven and line a tray."},
            {"number": 2, "text": "Mix mince with garlic, ginger, and spring onion, then roll into meatballs."},
            {"number": 3, "text": "Bake until cooked through.", "duration_minutes": 15},
            {"number": 4, "text": "Simmer soy sauce, honey, and a little water to form a sticky glaze, then toss meatballs through.", "duration_minutes": 4},
            {"number": 5, "text": "Serve with rice and sliced cucumber."},
        ],
    },
    {
        "id": "japanese_onigiri_tuna_mayo",
        "name": "Tuna Mayo Onigiri",
        "cuisine": "japanese",
        "equipment": ["hob"],
        "ingredients": ["rice", "tinned tuna", "mayonnaise", "salt", "nori sheets", "cucumber"],
        "cost": 2.40,
        "img": "https://images.unsplash.com/photo-1553621042-3e5f1f2a2c0f?auto=format&fit=crop&w=800&q=80",
        "nutrition": [610, 26, 96, 14],
        "steps": [
            {"number": 1, "text": "Cook rice and let it cool slightly until safe to handle.", "duration_minutes": 15},
            {"number": 2, "text": "Mix tuna with mayonnaise and a pinch of salt."},
            {"number": 3, "text": "Shape rice into triangles with a spoon of tuna filling in the centre."},
            {"number": 4, "text": "Wrap with nori and serve with sliced cucumber."},
        ],
    },
    {
        "id": "thai_pineapple_fried_rice_veg_gf",
        "name": "Pineapple Fried Rice (Vegetarian, Gluten-Free)",
        "cuisine": "thai",
        "equipment": ["hob"],
        "ingredients": ["cooked rice", "pineapple", "egg", "spring onion", "carrot", "peas", "tamari", "lime", "cashews"],
        "cost": 2.60,
        "img": "https://images.unsplash.com/photo-1546069901-2e2c2f9f9a2d?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 22, 108, 22],
        "steps": [
            {"number": 1, "text": "Scramble egg in a hot pan, then remove to a plate."},
            {"number": 2, "text": "Stir-fry carrot and peas until hot.", "duration_minutes": 4},
            {"number": 3, "text": "Add rice and pineapple and stir-fry until warmed through.", "duration_minutes": 5},
            {"number": 4, "text": "Stir in tamari, return egg, then finish with lime and cashews."},
        ],
    },
    {
        "id": "mexican_quesadilla_cheese_beans_veg",
        "name": "Cheese and Bean Quesadillas (Vegetarian)",
        "cuisine": "mexican",
        "equipment": ["hob"],
        "ingredients": ["tortilla wraps", "canned black beans", "cheddar", "spring onion", "salt", "salsa"],
        "cost": 2.20,
        "img": "https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [740, 30, 88, 30],
        "steps": [
            {"number": 1, "text": "Drain beans and mash lightly with a pinch of salt."},
            {"number": 2, "text": "Spread beans and cheddar over one tortilla, add spring onion, then top with another tortilla."},
            {"number": 3, "text": "Toast in a dry pan until golden on both sides and cheese melts.", "duration_minutes": 6},
            {"number": 4, "text": "Slice and serve with salsa."},
        ],
    },
    {
        "id": "british_veg_sausage_casserole_veg",
        "name": "Vegetarian Sausage Casserole",
        "cuisine": "british",
        "equipment": ["hob"],
        "ingredients": ["vegetarian sausages", "onion", "garlic", "canned tomatoes", "canned cannellini beans", "carrot", "vegetable stock", "dried thyme", "salt", "black pepper"],
        "cost": 2.90,
        "img": "https://images.unsplash.com/photo-1604908177477-7f2a6c1b2d7d?auto=format&fit=crop&w=800&q=80",
        "nutrition": [680, 26, 86, 24],
        "steps": [
            {"number": 1, "text": "Brown the vegetarian sausages, then set aside."},
            {"number": 2, "text": "Sauté onion, garlic, and carrot until softened."},
            {"number": 3, "text": "Add tomatoes, beans, stock, thyme, and sausages, then simmer until thick.", "duration_minutes": 18},
            {"number": 4, "text": "Season and serve."},
        ],
    },
    {
        "id": "mediterranean_halloumi_couscous_veg",
        "name": "Halloumi Couscous Salad (Vegetarian)",
        "cuisine": "mediterranean",
        "equipment": ["hob"],
        "ingredients": ["halloumi", "couscous", "vegetable stock", "cucumber", "cherry tomatoes", "olive oil", "lemon", "mint", "salt", "black pepper"],
        "cost": 3.90,
        "img": "https://images.unsplash.com/photo-1512621776951-8d2d1c2b7c1a?auto=format&fit=crop&w=800&q=80",
        "nutrition": [760, 30, 86, 34],
        "steps": [
            {"number": 1, "text": "Add couscous and hot stock to a bowl, cover, and let it steam.", "duration_minutes": 5},
            {"number": 2, "text": "Pan-sear halloumi slices until golden.", "duration_minutes": 4},
            {"number": 3, "text": "Fluff couscous, then toss with cucumber, tomatoes, mint, olive oil, lemon, salt, and pepper."},
            {"number": 4, "text": "Top with halloumi and serve."},
        ],
    },
    {
        "id": "american_salmon_potato_cakes",
        "name": "Salmon and Potato Cakes",
        "cuisine": "american",
        "equipment": ["hob"],
        "ingredients": ["tinned salmon", "potato", "spring onion", "egg", "salt", "black pepper", "lemon", "frozen peas"],
        "cost": 4.60,
        "img": "https://images.unsplash.com/photo-1543339308-9d2d9a2b5c1f?auto=format&fit=crop&w=800&q=80",
        "nutrition": [670, 36, 78, 24],
        "steps": [
            {"number": 1, "text": "Boil potatoes until tender, then mash and cool slightly.", "duration_minutes": 16},
            {"number": 2, "text": "Mix mash with salmon, spring onion, egg, salt, and pepper, then shape into patties."},
            {"number": 3, "text": "Pan-fry patties until golden on both sides.", "duration_minutes": 8},
            {"number": 4, "text": "Warm peas and serve with lemon wedges.", "duration_minutes": 3},
        ],
    },
    {
        "id": "chinese_garlic_ginger_noodles",
        "name": "Garlic Ginger Noodles",
        "cuisine": "chinese",
        "equipment": ["hob"],
        "ingredients": ["egg noodles", "garlic", "ginger", "soy sauce", "sesame oil", "spring onion", "broccoli"],
        "cost": 2.10,
        "img": "https://images.unsplash.com/photo-1525755662778-7f2a6b9c1d2e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [690, 20, 104, 20],
        "steps": [
            {"number": 1, "text": "Cook noodles according to packet instructions, then drain.", "duration_minutes": 6},
            {"number": 2, "text": "Stir-fry garlic and ginger briefly, then add broccoli and a splash of water to steam.", "duration_minutes": 4},
            {"number": 3, "text": "Toss noodles with soy sauce and a small drizzle of sesame oil."},
            {"number": 4, "text": "Top with spring onion and serve."},
        ],
    },
    {
        "id": "indian_tandoori_chicken_oven_gf",
        "name": "Tandoori Chicken Traybake (Gluten-Free)",
        "cuisine": "indian",
        "equipment": ["oven"],
        "ingredients": ["chicken thigh", "greek yogurt", "garlic", "ginger", "ground cumin", "ground coriander", "paprika", "turmeric", "salt", "lemon", "rice"],
        "cost": 4.90,
        "img": "https://images.unsplash.com/photo-1604908177499-4c2b1d8e7a1c?auto=format&fit=crop&w=800&q=80",
        "nutrition": [740, 48, 78, 28],
        "steps": [
            {"number": 1, "text": "Mix yogurt, garlic, ginger, spices, salt, and lemon juice."},
            {"number": 2, "text": "Coat chicken in the marinade and refrigerate if you have time.", "duration_minutes": 60},
            {"number": 3, "text": "Bake chicken until charred at the edges and cooked through.", "duration_minutes": 30},
            {"number": 4, "text": "Serve with rice."},
        ],
    },
    {
        "id": "japanese_soba_salad_gf_veg",
        "name": "Buckwheat Soba Salad (Vegetarian, Gluten-Free)",
        "cuisine": "japanese",
        "equipment": ["hob"],
        "ingredients": ["100 percent buckwheat soba noodles", "cucumber", "carrot", "spring onion", "sesame seeds", "tamari", "rice vinegar", "honey", "sesame oil"],
        "cost": 3.20,
        "img": "https://images.unsplash.com/photo-1546069901-1f1c2b3a4d5e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [610, 18, 94, 18],
        "steps": [
            {"number": 1, "text": "Cook soba noodles according to packet instructions, then rinse under cold water.", "duration_minutes": 6},
            {"number": 2, "text": "Julienne cucumber and carrot and add to a bowl with noodles."},
            {"number": 3, "text": "Whisk tamari, rice vinegar, honey, and sesame oil, then toss through."},
            {"number": 4, "text": "Top with spring onion and sesame seeds."},
        ],
    },
    {
        "id": "thai_peanut_chicken_noodles",
        "name": "Peanut Chicken Noodles",
        "cuisine": "thai",
        "equipment": ["hob"],
        "ingredients": ["chicken breast", "rice noodles", "peanut butter", "lime", "tamari", "garlic", "ginger", "carrot", "coriander"],
        "cost": 4.20,
        "img": "https://images.unsplash.com/photo-1512058564366-3f2a1b9c6d2e?auto=format&fit=crop&w=800&q=80",
        "nutrition": [780, 42, 96, 28],
        "steps": [
            {"number": 1, "text": "Soak rice noodles in hot water until pliable, then drain.", "duration_minutes": 8},
            {"number": 2, "text": "Stir-fry chicken until cooked through.", "duration_minutes": 6},
            {"number": 3, "text": "Whisk peanut butter, lime juice, tamari, garlic, ginger, and a splash of hot water into a sauce."},
            {"number": 4, "text": "Toss noodles and chicken with sauce, then top with carrot and coriander."},
        ],
    },
    {
        "id": "middle_eastern_falafel_bowls_veg",
        "name": "Falafel Bowls (Vegetarian)",
        "cuisine": "middle_eastern",
        "equipment": ["oven"],
        "ingredients": ["falafel", "rice", "cucumber", "tomato", "red onion", "hummus", "lemon", "olive oil", "salt"],
        "cost": 3.30,
        "img": "https://images.unsplash.com/photo-1540189549336-2a1b9c6d3e4f?auto=format&fit=crop&w=800&q=80",
        "nutrition": [720, 22, 102, 24],
        "steps": [
            {"number": 1, "text": "Bake falafel according to packet instructions until crisp.", "duration_minutes": 12},
            {"number": 2, "text": "Cook rice according to packet instructions.", "duration_minutes": 12},
            {"number": 3, "text": "Chop cucumber, tomato, and onion and season with lemon and olive oil."},
            {"number": 4, "text": "Assemble bowls with rice, salad, falafel, and hummus."},
        ],
    },
]

def seed_bulk():
    db = SessionLocal()
    added = 0
    for r in recipes:
        if db.query(RecipeModel).filter(RecipeModel.id == r["id"]).first():
            print(f"  Skipping (already exists): {r['id']}")
            continue
        recipe = RecipeModel(
            id=r["id"], name=r["name"], cuisine=r["cuisine"],
            required_equipment=r["equipment"], ingredients=r["ingredients"],
            base_cost_per_serving=r["cost"], image_url=r["img"],
            calories=r["nutrition"][0], protein_g=r["nutrition"][1],
            carbs_g=r["nutrition"][2], fat_g=r["nutrition"][3],
        )
        db.add(recipe)
        db.flush()
        for s in r["steps"]:
            db.add(RecipeStepModel(
                recipe_id=recipe.id, number=s["number"],
                text=s["text"], duration_minutes=s.get("duration_minutes")
            ))
        added += 1
    db.commit()
    db.close()
    print(f"Done. Added {added} new recipes.")

if __name__ == "__main__":
    seed_bulk()
